"""Data models for LLM-generated metadata."""

from pydantic import BaseModel


class ResponseMeta(BaseModel):
    """Metadata for an individual LLM response within a bundle."""

    platform: str
    model: str | None = None
    summary: str
    key_claims: list[str] = []
    stance: str | None = None


class BundleMeta(BaseModel):
    """Aggregate metadata for an entire bundle (generated by meta LLM)."""

    summary: str
    slug: str
    domains: list[str]
    topics: list[str]
    consensus: str | None = None
    divergence: str | None = None
    pending_topics: list[str] = []


class BundleFrontmatter(BaseModel):
    """Full frontmatter structure of a _bundle.md file (disk representation)."""

    id: str
    question: str | None = None
    summary: str
    slug: str
    domains: list[str]
    topics: list[str]
    pending_topics: list[str] = []
    platforms: list[str]
    created_at: str
    consensus: str | None = None
    divergence: str | None = None
